name: EzRedisLib
main: dev.unnm3d.ezredislib.platforms.EzRedisLibBukkit
author: Unnm3d
description: 'Bukkit implementation of EzRedisLib'
version: 2.2-Bukkit

commands:
  ezredislibreload:
    description: 'reloads redis connection'
permissions:
  ezredislib.reload:
    description: Allows you to reload the plugin
    default: op