name: EzRedisLib
main: dev.unnm3d.ezredislib.bukkit.EzRedisLibPlugin
author: Unnm3d
description: 'Bukkit implementation of EzRedisLib'
version: 1.0-Bukkit

commands:
  ezredislibreload:
    description: 'reloads redis connection'
permissions:
  ezredislibreload:
    description: Allows you to reload the plugin
    default: op